package homewallet;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import homewallet.Product;
import homewallet.ProductRepository;

@Controller
public class ProductController {
    @Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private ProductRepository productRepository;

    @GetMapping("/product")
    public String product(Model model){
        model.addAttribute("action", "view");
        return "product";
    }

    @RequestMapping(value="/product/add", method = RequestMethod.GET)
    public String add(Model model) {
        // create a new product
        Product newProduct = new Product();
        newProduct.setName("a product");
        newProduct.setCost("11.33");
        productRepository.save(newProduct);
        model.addAttribute("action", "add");
        return "product";
    }

    @RequestMapping(value="/product/all", method = RequestMethod.GET)
    public @ResponseBody Iterable<Product> getAllProducts() {
        // this returns a JSON or XML with the products
        return productRepository.findAll();
    }

    @RequestMapping(value="/product/delete", method = RequestMethod.GET)
    public String delete(Model model) {
        model.addAttribute("action", "delete");
        return "product";
    }

    @RequestMapping(value="/product/update", method = RequestMethod.GET)
    public String update(Model model) {
        model.addAttribute("action", "update");
        return "product";
    }

}